version: "2.3"
services:
  androgee:
    build:
      context: .
      args:
        discord_token: $DISCORD_TOKEN
        rust_ip: $RUST_IP
        rust_port: $RUST_PORT
        rust_password: $RUST_PASSWORD
        minecraft_ip: $MINECRAFT_IP
        minecraft_port: $MINECRAFT_PORT
        minecraft_password: $MINECRAFT_PASSWORD